#!/usr/bin/env bash

set -e

LANGUAGES=("bash" "haskell" "python")

echo "Cleaning up"
cabal clean

echo "Updating"
cabal update

echo "Building"
cabal build

echo "Testing"
cabal test

# Sample scripts.
CACHE_PATH=$(mktemp -u -d -t magix-XXXXXX)
echo "Temporary cache path is ${CACHE_PATH}"
for l in "${LANGUAGES[@]}"; do
    echo "Running sample scripts for language ${l}"
    dir="test-scripts/${l}"
    cabal run magix -- --cache-path "${CACHE_PATH}" -v "${dir}/empty"
    cabal run magix -- --cache-path "${CACHE_PATH}" -v "${dir}/minimal"
    cabal run magix -- --cache-path "${CACHE_PATH}" -v "${dir}/minimal with spaces"
    cabal run magix -- --cache-path "${CACHE_PATH}" -v "${dir}/args" -h and other args
done

# Parallel builds.
CACHE_PATH_PARALLEL=$(mktemp -u -d -t magix-XXXXXX)
# We assume `magix' has been built.
MAGIX=$(cabal list-bin magix)
echo "Temporary cache path for parallel builds is ${CACHE_PATH_PARALLEL}"
for l in "${LANGUAGES[@]}"; do
    echo "Running parallel builds for language ${l}"
    dir="test-scripts/${l}"
    # We use `cabal exec`, because `cabal run` leads to weird linker errors
    # and core dumps... (Why)?
    parallel -N0 \
        cabal exec -- "${MAGIX}" --cache-path "${CACHE_PATH_PARALLEL}" -v "${dir}/minimal" \
        ::: {1..10}
done
