#!/usr/bin/env bash

set -e

PROJ_ROOT=$(git rev-parse --show-toplevel)
cd "${PROJ_ROOT}"

fn=cabal.project.freeze
tmp=cabal.project.freeze.tmp

rm $fn
cabal freeze

mv $fn $tmp

echo active-repositories: hackage.haskell.org >$fn
tail -n +2 $tmp >>$fn
rm $tmp
